name: bebop
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  firebase_storage: ^11.2.1
  cloud_firestore: ^4.7.1

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.16
  fluttertoast: ^8.1.2
  page_transition: ^2.0.9
  flutter_spinkit: ^5.1.0
  flutter_bloc: ^8.1.1
  lottie: ^2.2.0
  sizer: ^2.0.15
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  font_awesome_flutter: ^10.3.0
  flutter_svg: ^1.1.6
  rounded_loading_button: ^2.1.0
  custom_sliding_segmented_control: ^1.7.4
  intl: ^0.18.0
  syncfusion_flutter_sliders: ^20.4.48
  smooth_page_indicator: ^1.0.0+2
  animated_bottom_navigation_bar: ^1.1.0+1
  circular_reveal_animation: ^2.0.1
  flutter_speed_dial: ^6.2.0
  carousel_slider: ^4.2.1
  syncfusion_flutter_charts: ^20.4.49
  image_picker: ^0.8.6+1
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  syncfusion_flutter_gauges: ^20.4.51
  firebase_crashlytics: ^3.2.0
  connectivity_plus: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

  fonts:

    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Mukta-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mukta-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mukta-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mukta-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mukta-Light.ttf
          weight: 300
        - asset: assets/fonts/Mukta-ExtraLight.ttf
          weight: 200


    - family: Guyon Gazebo
      fonts:
        - asset: assets/fonts/Gazebo DEMO.otf
