name: bebop
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.16
  fluttertoast: ^8.1.2
  page_transition: ^2.0.9
  flutter_spinkit: ^5.1.0
  flutter_bloc: ^8.1.1
  lottie: ^2.2.0
  sizer: ^2.0.15
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/json/

  fonts:
     - family: Crimson Pro
       fonts:
         - asset: assets/fonts/CrimsonPro-Black.ttf
           weight: 900
         - asset: assets/fonts/CrimsonPro-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/CrimsonPro-Bold.ttf
           weight: 700
         - asset: assets/fonts/CrimsonPro-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/CrimsonPro-Medium.ttf
           weight: 500
         - asset: assets/fonts/CrimsonPro-Regular.ttf
           weight: 400
         - asset: assets/fonts/CrimsonPro-light.ttf
           weight: 300
         - asset: assets/fonts/CrimsonPro-ExtraLight.ttf
           weight: 200


     - family: Guyon Gazebo
       fonts:
         - asset: assets/fonts/Gazebo DEMO.otf


     - family: Wasser
       fonts:
         - asset: assets/fonts/wasser.ttf

